[package]
name = "meow-zip"
edition = "2024"

[dependencies]
libmeow = { path = "../libmeow" }
clap = { version = "4.0", features = ["derive"] }
eyre = "0.6.12"
color-eyre = "0.6.5"
minisign = "0.7.9"
zstd = "0.13.3"
dirs = "6.0.0"
file-mode = "0.1.2"
owo-colors = "4.2.3"
humansize = "2.1.3"
